name: Build and package RoBERTa-sequencing to Dockerhub
on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Az CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        if: runner.os == 'Linux' || runner.os == 'macOS'

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Set auto-install of extensions
        run: az config set extension.use_dynamic_install=yes_without_prompt

      - name: Attach workspace
        run: az ml folder attach -w "ml-ws" -g "azure-ml-1"

      - name: Retrieve the model
        run: az ml model download -t "." --model-id "distilbert-model"

      - name: Build Flask app container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: alfredodeza/flask-roberta:latest
